export const T = {
  save: 'save', cancel: 'cancel', delete: 'delete', edit: 'edit', add: 'add',
  done: 'done', skip: 'skip', optional: 'optional', today: 'today',
  navToday: 'today', navPlanner: 'planner', navHistory: 'history',
  hello: 'hey there',
  startLearning: "let's go ✨", stopSession: 'stop',
  learning: 'in the zone…',
  readyWhenYouAre: 'when you\'re ready 🫴',
  todayTotal: 'today',
  sessionsToday: "sessions today",
  todaysPlan: "today's plan",
  noPlanForToday: "no plan for today.",
  planOne: 'add one',
  addPastSession: '+ log a past session',
  freshStart: "let's get this engine started 🚗",

  // Post-stop prompt — optional, can skip
  postStopTitle: 'nice 🌱',
  postStopAsk: 'what did you learn? (optional)',
  postStopPlaceholder: 'just a line is fine…',
  postStopSave: 'save',
  postStopSkip: 'skip',

  plannerTitle: 'planner',
  goalPlaceholder: 'e.g. learn 10–12, biology ch 3, 2h math…',
  addPlan: '+ add',
  date: 'date',
  noPlans: 'nothing here yet',
  skipDay: 'not learning today',
  markSkipDay: 'mark as not-learning 🌿',
  unmarkSkipDay: "actually i am learning",
  skipDayGreeting: 'no learning today 🌿',
  skipDaySub: 'see you tomorrow ✨',
  skipDayMaybeStart: 'sneaking in a quick one? 👀',
  sessionStartEnd: 'start & end time',
  sessionDuration: 'duration',
  startTime: 'start', endTime: 'end',
  howManyMinutes: 'how many minutes?',
  whatDidYouLearn: 'what did you work on?',
  notesPlaceholder: 'e.g. algebra, chapter 3…',
  shortSession: 'short session',
  longSession: 'long session',
  historyTitle: 'history',
  past7: '7 days', allTime: 'all time',
  totalThisWeek: 'this week',
  light: 'light ☀️', dark: 'dark 🌙',
  weekdayShort: ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'],
  monthView: 'month', weekView: 'week',
  checkPlan: 'mark done',
  addToDay: '+ session',
  freeDay: 'free day',

  // ---- Mascot lines ----
  // Edit freely. One shown per visit (random each time).
  // Tone: chatty, lightly insistent, jokingly bossy. Never mean. Never about
  // her body or appearance. Lines stay under ~30 chars so the bubble fits.
  mascotLines: [
    "cmon cmon i know you're there",
    "nah u can do it 💪",
    "the engine wants ON 🔥",
    "five minutes. just five.",
    "okay frog says GO",
    "let's keep this going ✨",
    "even a little counts",
    "you better! 🩴",  // כפכף צדק
    "👁️ i'm watching",
    "you literally can",
    "go go go go go 🚗",
    "back so soon? good ✨",
    "let's gooooo 🌟",
    "engine warming, hop in 🐸",
    "a tiny start works",
    "ribbit ribbit",
  ],
};
