export const T = {
  save: 'save', cancel: 'cancel', delete: 'delete', edit: 'edit', add: 'add',
  done: 'done', skip: 'skip', optional: 'optional', today: 'today',
  navToday: 'today', navPlanner: 'planner', navHistory: 'history',
  hello: 'hey there',
  startLearning: "let's go", stopSession: 'stop',
  learning: 'in the zone…',
  readyWhenYouAre: 'when you\'re ready 🫴',
  todayTotal: 'today',
  sessionsToday: "sessions today",
  todaysPlan: "today's plan",
  noPlanForToday: "no plan for today.",
  planOne: 'add one',
  addPastSession: '+ log a past session',
  freshStart: "let's get this engine started 🚗",

  // Post-stop prompt — optional, can skip
  postStopTitle: 'nice 🌱',
  postStopAsk: 'what did you learn? (optional)',
  postStopPlaceholder: 'just a line is fine…',
  postStopSave: 'save',
  postStopSkip: 'skip',

  plannerTitle: 'planner',
  goalPlaceholder: 'e.g. learn 10–12, biology ch 3, 2h math…',
  addPlan: '+ add',
  date: 'date',
  noPlans: 'nothing here yet',
  skipDay: 'not learning today',
  markSkipDay: 'mark as not-learning 🌿',
  unmarkSkipDay: "actually i am learning",
  skipDayGreeting: 'no learning today 🌿',
  skipDaySub: 'see you tomorrow ✨',
  skipDayMaybeStart: 'sneaking in a quick one? 👀',
  sessionStartEnd: 'start & end time',
  sessionDuration: 'duration',
  startTime: 'start', endTime: 'end',
  howManyMinutes: 'how many minutes?',
  whatDidYouLearn: 'what did you work on?',
  notesPlaceholder: 'e.g. algebra, chapter 3…',
  historyTitle: 'history',
  past7: '7 days', allTime: 'all time',
  totalThisWeek: 'this week',
  weekdayShort: ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'],
  monthView: 'month', weekView: 'week',
  checkPlan: 'mark done',
  addToDay: '+ session',
  freeDay: 'free day',

  mascotLines: [
    "cmon cmon i know you're there",
    "u can do it 💪",
    "pls 🥺👉👈",
    "anything at all 😫",
    "you better! 🩴",  // כפכף צדק
    "👁️ i'm watching",
    "ribbit ribbit",
  ],
};
